### ISSUE TITLE
Hubitat not loaded -- can't install

### ISSUE THREAD

**Issue by bwonish** [jason0x43/hacs-hubitat#271]
I am attempting to install hubitat through HACS (Devices / Integrations / Add Integration / Select Hubitat) and I receive an error:

Error
Config flow could not be loaded: {"message":"Invalid handler specified"}

I have had Hubitat installed and connected for a while with approximately 100 devices working great.  I recently noticed I was getting an error that Hubitat would not load (similar to this issue: https://github.com/jason0x43/hacs-hubitat/issues/248).  In an effort to troubleshoot, I uninstalled Hubitat and tried to re-install to make sure I had the latest version.

After getting Hubitat to uninstall, I cannot get it to re-install.  I continue to get the error message above.

Core: 2024.4.2
Supervisor: 2024.04.0
Operating System 12.2
Frontend 20240404.1

Hubitat version: 2.3.8.139

Prior to uninstalling the Integration, I was receiving the following errors messages:

Error 1:

Logger: homeassistant.config_entries
Source: config_entries.py:2589
First occurred: 1:08:43 PM (2 occurrences)
Last logged: 1:09:53 PM

Error occurred loading flow for integration hubitat: Exception importing custom_components.hubitat.config_flow

Error 2:

Logger: homeassistant.loader
Source: loader.py:1232
First occurred: 1:08:43 PM (4 occurrences)
Last logged: 1:09:53 PM

Unexpected exception importing platform custom_components.hubitat.config_flow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1232, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/hubitat/__init__.py", line 9, in <module>
    from custom_components.hubitat.services import (
  File "/config/custom_components/hubitat/services.py", line 11, in <module>
    from .alarm_control_panel import HubitatSecurityKeypad
  File "/config/custom_components/hubitat/alarm_control_panel.py", line 23, in <module>
    from .device import HubitatEntity
  File "/config/custom_components/hubitat/device.py", line 133, in <module>
    class HubitatEntity(HubitatBase, UpdateableEntity):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases

===================================================

Any help or ideas on how to troubleshoot this or get Hubitat's integration re-installed would be appreciated.

Thank you!

~~~~~~~~~~~~~~~

FYI - I have also been receiving an additional Warning and wanted to make sure the right people were aware of this future issue:

Logger: homeassistant.components.alarm_control_panel
Source: helpers/deprecation.py:206
integration: Alarm control panel (documentation, issues)
First occurred: 1:08:43 PM (32 occurrences)
Last logged: 1:09:53 PM

SUPPORT_ALARM_TRIGGER was used from hubitat, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.TRIGGER instead, please report it to the author of the 'hubitat' custom integration
SUPPORT_ALARM_ARM_AWAY was used from hubitat, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_AWAY instead, please create a bug report at https://github.com/jason0x43/hacs-hubitat/issues
SUPPORT_ALARM_ARM_HOME was used from hubitat, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_HOME instead, please create a bug report at https://github.com/jason0x43/hacs-hubitat/issues
SUPPORT_ALARM_ARM_NIGHT was used from hubitat, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_NIGHT instead, please create a bug report at https://github.com/jason0x43/hacs-hubitat/issues
SUPPORT_ALARM_TRIGGER was used from hubitat, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.TRIGGER instead, please create a bug report at https://github.com/jason0x43/hacs-hubitat/issues

**Comment by jason0x43** [comment]
What version of the integration does HACS say it’s trying to install? The current version is 0.9.26. Both the metaclass error (or at least _a_ metaclass error) and alarm deprecation warnings were resolved several versions ago.

**Comment by bwonish** [comment]
Honestly, when I was in HomeAssistant, I couldn't find a version anywhere.  I went into the Studio Code Server, under config / custom components / hubitat, the _init_py is showing version 0.6.1.  apparently earlier, i wasn't able to delete the integration, but was able to disable it.  i re-enabled it and it still showed as it couldn't load.  I clicked on the trashbin, but it doesn't appear to delete/uninstall.  i went into HACS and downloaded the current version 0.9.26.  it loaded and all the connections appear to be working.  

So it seems like i have an old integration installed and I am not sure how to completely remove it (or if it is necessary).  For tonight, it looks like installing (or reinstalling) through HACS fixed my issues.  

Thanks for responding.  Unless you would advise continuing to work on it to get rid of the old integration, I think I am good.
